name: apply

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.IAM_ROLE_NAME }}
  TF_VERSION: 1.9.2
  AWS_DEFAULT_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup aqua
        uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.28.0
          aqua_opts: ""

      - name: Install tools via Aqua
        run: |
          aqua install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Initialize Terragrunt
        working-directory: environments/prod
        run: terragrunt init --terragrunt-non-interactive

      - name: Apply Terragrunt configuration
        working-directory: environments/prod
        run: terragrunt apply --terragrunt-non-interactive