name: apply

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.IAM_ROLE_NAME }}
  TF_VERSION: 1.9.2
  AWS_DEFAULT_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: read

jobs:
  apply-terragrunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/workflows/common_setup.yml

      - name: Initialize Terragrunt
        working-directory: environments/prod
        run: terragrunt run-all init --terragrunt-non-interactive

      - name: Apply Terragrunt configuration
        working-directory: environments/prod
        run: terragrunt run-all apply --terragrunt-non-interactive
