name: Common Setup

on:
  workflow_call:
    secrets:
      AWS_ROLE_ARN:
        required: true
      AWS_DEFAULT_REGION:
        required: true

jobs:
  common-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup aqua
        uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.28.0
          aqua_opts: ""

      - name: Install tools via Aqua
        run: aqua install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
