name: plan

on:
  push:
    branches:
      - feature/**

env:
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.IAM_ROLE_NAME }}
  TF_VERSION: 1.9.2
  AWS_DEFAULT_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup aqua
        uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.28.0
          aqua_opts: ""

      - name: Install tools via Aqua
        run: |
          aqua install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Run TFsec
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tfsec --format=checkstyle | reviewdog -f=checkstyle -name="tfsec" -reporter=github-pr-review -filter-mode=nofilter -fail-on-error

      - name: Run TFlint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tflint --init
          tflint --format=checkstyle | reviewdog -f=checkstyle -name="tflint" -reporter=github-pr-review -filter-mode=nofilter -fail-on-error

      - name: Initialize Terragrunt
        working-directory: environments/prod
        run: terragrunt init --terragrunt-non-interactive

      - name: Check Terragrunt format
        working-directory: environments/prod
        run: terragrunt fmt -check

      - name: Validate Terragrunt
        working-directory: environments/prod
        run: terragrunt validate

      - name: Run Terragrunt plan
        working-directory: environments/prod
        run: terragrunt plan

  create-pr:
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request for Apply
        if: startsWith(github.ref, 'refs/heads/feature/')
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Run security and format checks"
          branch: main
          title: "Merge feature branch into main"
          body: "This PR merges the feature branch into main and includes security and format checks."
